$(document).ready(function(){
$('.slider').slick({
    arrows:true, 
    dots:true,
    adaptiveHeight:false,
    speed:1000,
    easing:'ease',
    autoplay:true,
    autoplaySpeed:30000,
    waitForAnimate:false
});
});